Update github actions

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -8,10 +8,6 @@ on:
     # Build when main or testing is pushed to
     branches:
       - main
-  pull_request:
-    # Build when a pull request targets main
-    branches:
-      - main
 
 
 jobs:
@@ -22,56 +18,104 @@ jobs:
       run:
         shell: bash -l {0}
     steps:
-      - uses: actions/checkout@v2
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: 3.7
-          mamba-version: "*"
-          channels: conda-forge,cantera/label/dev,defaults
-          channel-priority: true
-          activate-environment: ctwrap
-          environment-file: environment.yml
-          #auto-activate-base: false
-      - name: Check conda status
-        run: |
-          conda info
-          conda list
-      - name: Install ctwrap
-        run: |
-          pip install -e .
-      - name: Run pytest
-        run: pytest
-      - name: Get coverage
-        run: coverage report
+    - uses: actions/checkout@v2
+    - uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: 3.7
+        mamba-version: "*"
+        channels: conda-forge,cantera/label/dev,defaults
+        channel-priority: true
+        activate-environment: ctwrap
+        environment-file: environment.yml
+        #auto-activate-base: false
+    - name: Check conda status
+      run: |
+        conda info
+        conda list
+    - name: Install ctwrap
+      run: |
+        pip install -e .
+    - name: Run pytest
+      run: pytest
+    - name: Get coverage
+      run: coverage report
+
+  nosetests-win:
+    name: Run pytest on Windows
+    runs-on: "windows-latest"
+    defaults:
+      run:
+        shell: bash -l {0}
+    steps:
+    - uses: actions/checkout@v2
+    - uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: 3.7
+        mamba-version: "*"
+        channels: conda-forge,cantera/label/dev,defaults
+        channel-priority: true
+        activate-environment: ctwrap
+        environment-file: environment.yml
+        #auto-activate-base: false
+    - name: Check conda status
+      run: |
+        conda info
+        conda list
+    - name: Install ctwrap
+      run: |
+        pip install -e .
+    - name: Run pytest
+      run: pytest
+
+  sphinx-build:
+    name: Build Sphinx docs on Linux
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -l {0}
+    steps:
+    - uses: actions/checkout@v2
+    - uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: 3.7
+        mamba-version: "*"
+        channels: conda-forge,cantera/label/dev,defaults
+        channel-priority: true
+        activate-environment: ctwrap
+        environment-file: environment.yml
+        #auto-activate-base: false
+    - name: Check conda status
+      run: |
+        conda info
+        conda list
+    - name: Install ctwrap
+      run: |
+        pip install -e .
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        #build-command: "sphinx-build -b html . _build"
+        docs-folder: "docs/"
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
 
   # nosetests-mac:
   #   name: OSX
   #   runs-on: "macos-latest"
-
-# # tests on windows are slow (!)
-#   nosetests-win:
-#     name: Run pytest on Windows
-#     runs-on: "windows-latest"
-#     defaults:
-#       run:
-#         shell: bash -l {0}
-#     steps:
-#       - uses: actions/checkout@v2
-#       - uses: conda-incubator/setup-miniconda@v2
-#         with:
-#           python-version: 3.7
-#           mamba-version: "*"
-#           channels: conda-forge,cantera/label/dev,defaults
-#           channel-priority: true
-#           activate-environment: ctwrap
-#           environment-file: environment.yml
-#           #auto-activate-base: false
-#       - name: Check conda status
-#         run: |
-#           conda info
-#           conda list
-#       - name: Install ctwrap
-#         run: |
-#           pip install -e .
-#       - name: Run pytest
-#         run: pytest
